apiVersion: v1
kind: Service
metadata:
  name: remoxa-service
spec:
  type: NodePort
  selector:
    app: remoxa
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
